action: train # train or test
name: trainClassifier
split: train
resume_from: ./saved_models/I3D_SourceOnlyD1

save:
  num_clips: 5
  dense_sampling:
    RGB: True
  num_frames_per_clip:
    RGB: 10

train:
  num_iter: ??
  num_clips: 5
  num_frames_per_clip: ??
  dense_sampling:
    RGB: True
  num_frames_per_clip:
    RGB: 10 

test:
  num_clips: ??
  num_frames_per_clip: ??


dataset:
  annotations_path: train_val
  shift: D1-D1
  workers: 4
  stride: 2
  resolution: 224
  num_classes: 8
  RGB:
    data_path: ../ek_data/frames
    tmpl: "img_{:010d}.jpg"
    features_name: ?? #can be removed later if problematic
  Event:
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: ??
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    weight_i3d_rgb: './pretrained_i3d/rgb_imagenet.pt'


